-- =====================================================================
-- 06_security.sql
-- Same definition, different entitlement:
--   * Row access policy scopes each persona to its plants
--     (all three personas can see Chennai, so the demo compares like for like)
--   * Logistics cannot see commercial prices (masking)
--   * Tags for domain and certification
--   * Grants on the semantic view and governed objects
-- Re-run after 04_conformed.sql, because CREATE OR REPLACE drops policies.
-- =====================================================================
USE ROLE SC_ADMIN;
USE WAREHOUSE SC_WH;
USE DATABASE SC_ONTOLOGY;

CREATE OR REPLACE TABLE GOVERNED.PERSONA_PLANT_SCOPE (role_name STRING, plant_id STRING);
INSERT INTO GOVERNED.PERSONA_PLANT_SCOPE VALUES
  ('SC_PLANNING','IN01'), ('SC_PLANNING','JP01'), ('SC_PLANNING','GB01'), ('SC_PLANNING','US01'), ('SC_PLANNING','MX01'),
  ('SC_PROCUREMENT','IN01'), ('SC_PROCUREMENT','JP01'), ('SC_PROCUREMENT','US01'),
  ('SC_LOGISTICS','IN01'), ('SC_LOGISTICS','GB01');

-- Detach before replacing the policy
ALTER TABLE CONFORMED.FCT_PO_LINE            DROP ALL ROW ACCESS POLICIES;
ALTER TABLE CONFORMED.FCT_ORDER_LINE         DROP ALL ROW ACCESS POLICIES;
ALTER TABLE CONFORMED.FCT_SHIPMENT           DROP ALL ROW ACCESS POLICIES;
ALTER TABLE CONFORMED.FCT_INVENTORY_POSITION DROP ALL ROW ACCESS POLICIES;

CREATE OR REPLACE ROW ACCESS POLICY GOVERNED.RAP_PLANT_SCOPE
  AS (p_plant_id STRING) RETURNS BOOLEAN ->
    CURRENT_ROLE() = 'SC_ADMIN'
    OR EXISTS (
      SELECT 1 FROM SC_ONTOLOGY.GOVERNED.PERSONA_PLANT_SCOPE s
      WHERE s.role_name = CURRENT_ROLE() AND s.plant_id = p_plant_id
    );

ALTER TABLE CONFORMED.FCT_PO_LINE            ADD ROW ACCESS POLICY GOVERNED.RAP_PLANT_SCOPE ON (plant_id);
ALTER TABLE CONFORMED.FCT_ORDER_LINE         ADD ROW ACCESS POLICY GOVERNED.RAP_PLANT_SCOPE ON (plant_id);
ALTER TABLE CONFORMED.FCT_SHIPMENT           ADD ROW ACCESS POLICY GOVERNED.RAP_PLANT_SCOPE ON (plant_id);
ALTER TABLE CONFORMED.FCT_INVENTORY_POSITION ADD ROW ACCESS POLICY GOVERNED.RAP_PLANT_SCOPE ON (plant_id);

-- Commercial price masking for Logistics
CREATE MASKING POLICY IF NOT EXISTS GOVERNED.MASK_COMMERCIAL_PRICE
  AS (val NUMBER(38,4)) RETURNS NUMBER(38,4) ->
    CASE WHEN CURRENT_ROLE() = 'SC_LOGISTICS' THEN NULL ELSE val END;

ALTER TABLE CONFORMED.FCT_PO_LINE MODIFY COLUMN unit_price_local SET MASKING POLICY GOVERNED.MASK_COMMERCIAL_PRICE FORCE;
ALTER TABLE CONFORMED.FCT_PO_LINE MODIFY COLUMN unit_price_usd   SET MASKING POLICY GOVERNED.MASK_COMMERCIAL_PRICE FORCE;

-- Tags
CREATE TAG IF NOT EXISTS GOVERNED.DATA_DOMAIN
  ALLOWED_VALUES 'PROCUREMENT', 'ORDER_TO_DELIVERY', 'LOGISTICS', 'INVENTORY', 'MASTER_DATA';
CREATE TAG IF NOT EXISTS GOVERNED.CERTIFICATION
  ALLOWED_VALUES 'CERTIFIED', 'DRAFT', 'DEPRECATED';

ALTER TABLE CONFORMED.FCT_PO_LINE            SET TAG GOVERNED.DATA_DOMAIN = 'PROCUREMENT',       GOVERNED.CERTIFICATION = 'CERTIFIED';
ALTER TABLE CONFORMED.FCT_ORDER_LINE         SET TAG GOVERNED.DATA_DOMAIN = 'ORDER_TO_DELIVERY', GOVERNED.CERTIFICATION = 'CERTIFIED';
ALTER TABLE CONFORMED.FCT_SHIPMENT           SET TAG GOVERNED.DATA_DOMAIN = 'LOGISTICS',         GOVERNED.CERTIFICATION = 'CERTIFIED';
ALTER TABLE CONFORMED.FCT_INVENTORY_POSITION SET TAG GOVERNED.DATA_DOMAIN = 'INVENTORY',         GOVERNED.CERTIFICATION = 'CERTIFIED';
ALTER TABLE CONFORMED.DIM_SUPPLIER           SET TAG GOVERNED.DATA_DOMAIN = 'MASTER_DATA',       GOVERNED.CERTIFICATION = 'CERTIFIED';
ALTER TABLE CONFORMED.XREF_SUPPLIER          SET TAG GOVERNED.DATA_DOMAIN = 'MASTER_DATA',       GOVERNED.CERTIFICATION = 'CERTIFIED';

-- Grants: planning
GRANT USAGE  ON DATABASE SC_ONTOLOGY                 TO ROLE SC_PLANNING;
GRANT USAGE  ON SCHEMA SC_ONTOLOGY.CONFORMED          TO ROLE SC_PLANNING;
GRANT USAGE  ON SCHEMA SC_ONTOLOGY.GOVERNED           TO ROLE SC_PLANNING;
GRANT SELECT ON ALL TABLES IN SCHEMA SC_ONTOLOGY.CONFORMED TO ROLE SC_PLANNING;
GRANT SELECT ON TABLE SC_ONTOLOGY.GOVERNED.METRIC_REGISTRY TO ROLE SC_PLANNING;
GRANT SELECT ON VIEW  SC_ONTOLOGY.GOVERNED.V_CANONICAL_SCORECARD TO ROLE SC_PLANNING;
GRANT SELECT ON SEMANTIC VIEW SC_ONTOLOGY.GOVERNED.SUPPLY_CHAIN_ONTOLOGY TO ROLE SC_PLANNING;

-- Grants: procurement
GRANT USAGE  ON DATABASE SC_ONTOLOGY                 TO ROLE SC_PROCUREMENT;
GRANT USAGE  ON SCHEMA SC_ONTOLOGY.CONFORMED          TO ROLE SC_PROCUREMENT;
GRANT USAGE  ON SCHEMA SC_ONTOLOGY.GOVERNED           TO ROLE SC_PROCUREMENT;
GRANT SELECT ON ALL TABLES IN SCHEMA SC_ONTOLOGY.CONFORMED TO ROLE SC_PROCUREMENT;
GRANT SELECT ON TABLE SC_ONTOLOGY.GOVERNED.METRIC_REGISTRY TO ROLE SC_PROCUREMENT;
GRANT SELECT ON VIEW  SC_ONTOLOGY.GOVERNED.V_CANONICAL_SCORECARD TO ROLE SC_PROCUREMENT;
GRANT SELECT ON SEMANTIC VIEW SC_ONTOLOGY.GOVERNED.SUPPLY_CHAIN_ONTOLOGY TO ROLE SC_PROCUREMENT;

-- Grants: logistics
GRANT USAGE  ON DATABASE SC_ONTOLOGY                 TO ROLE SC_LOGISTICS;
GRANT USAGE  ON SCHEMA SC_ONTOLOGY.CONFORMED          TO ROLE SC_LOGISTICS;
GRANT USAGE  ON SCHEMA SC_ONTOLOGY.GOVERNED           TO ROLE SC_LOGISTICS;
GRANT SELECT ON ALL TABLES IN SCHEMA SC_ONTOLOGY.CONFORMED TO ROLE SC_LOGISTICS;
GRANT SELECT ON TABLE SC_ONTOLOGY.GOVERNED.METRIC_REGISTRY TO ROLE SC_LOGISTICS;
GRANT SELECT ON VIEW  SC_ONTOLOGY.GOVERNED.V_CANONICAL_SCORECARD TO ROLE SC_LOGISTICS;
GRANT SELECT ON SEMANTIC VIEW SC_ONTOLOGY.GOVERNED.SUPPLY_CHAIN_ONTOLOGY TO ROLE SC_LOGISTICS;
