"""
Governed supply chain analytics (Streamlit in Snowflake).

Tabs
  Ask               governed chat over the semantic view, with SQL, metric cards and audit
  Persona face-off  one metric, three teams' wording, one answer
  Consistency test  persona, hostile and entitlement tests against the golden answers
  Before and after  legacy team logic vs the certified metric, and the gap explained rule by rule
  Governance        change a certified definition live, with version bump and change log
  Metric catalog    ontology graph, registry, parameters, supplier crosswalk, audit log

Works on the warehouse runtime and the container runtime, and on older Streamlit
versions. Deploy into SC_ONTOLOGY.APP with owner role SC_ADMIN and warehouse SC_WH.
"""
from __future__ import annotations

import json
import os
import re
import uuid
from datetime import datetime

import altair as alt
import pandas as pd
import requests
import streamlit as st
from snowflake.snowpark.context import get_active_session

try:  # warehouse runtime
    import _snowflake
except ImportError:  # container runtime
    _snowflake = None

DB = "SC_ONTOLOGY"
SEMANTIC_VIEW = f"{DB}.GOVERNED.SUPPLY_CHAIN_ONTOLOGY"
ANALYST_ENDPOINT = "/api/v2/cortex/analyst/message"
ANALYST_TIMEOUT_MS = 50_000
RATIO_TOLERANCE = 0.0005
PERSONAS = ["PLANNING", "PROCUREMENT", "LOGISTICS"]

# Chart colours (legacy = neutral, gains/losses = diverging blue/red, certified = deep blue)
C_LEGACY, C_UP, C_DOWN, C_CERT = "#8a8a86", "#2a78d6", "#e34948", "#184f95"

st.set_page_config(page_title="Supply chain ontology", page_icon="🔗", layout="wide")
session = get_active_session()


# ---------------------------------------------------------------- data access
@st.cache_data(ttl=300)
def load_governed(table: str) -> pd.DataFrame:
    return session.table(f"{DB}.GOVERNED.{table}").to_pandas()


def run_sql(sql: str, params: list | None = None) -> pd.DataFrame:
    df = session.sql(sql.strip().rstrip(";"), params=params).to_pandas() if params \
        else session.sql(sql.strip().rstrip(";")).to_pandas()
    df.columns = [str(c).upper() for c in df.columns]
    return df


WRITE_WORDS = re.compile(
    r"\b(INSERT|UPDATE|DELETE|MERGE|DROP|TRUNCATE|CREATE|ALTER|GRANT|REVOKE|CALL|COPY|PUT|GET|REMOVE|"
    r"EXECUTE|UNDROP|USE|SET|UNSET)\b", re.I)


def is_read_only(sql: str | None) -> bool:
    """Only single SELECT / WITH statements generated by the NL layer are ever executed."""
    body = re.sub(r"--[^\n]*|/\*.*?\*/", " ", sql or "", flags=re.S)
    body = re.sub(r"'(?:[^']|'')*'", "''", body).strip().rstrip(";").strip()
    if not body:
        return False
    first = body.split(None, 1)[0].upper()
    return first in ("SELECT", "WITH") and ";" not in body and not WRITE_WORDS.search(body)


# ------------------------------------------------------------ Cortex Analyst
SPCS_TOKEN_FILE = "/snowflake/session/token"


def _rest_target():
    """Host and auth headers for calling the Snowflake REST API from the container runtime."""
    if os.path.exists(SPCS_TOKEN_FILE):
        with open(SPCS_TOKEN_FILE) as f:
            token = f.read().strip()
        host = os.environ.get("SNOWFLAKE_HOST") or session.connection.host
        headers = {"Authorization": f"Bearer {token}",
                   "X-Snowflake-Authorization-Token-Type": "OAUTH"}
    else:
        host = session.connection.host
        headers = {"Authorization": f'Snowflake Token="{session.connection.rest.token}"'}
    headers.update({"Content-Type": "application/json", "Accept": "application/json"})
    return host, headers


def call_analyst(messages: list) -> dict:
    body = {"messages": messages, "semantic_view": SEMANTIC_VIEW}
    if _snowflake is not None:
        resp = _snowflake.send_snow_api_request(
            "POST", ANALYST_ENDPOINT, {}, {}, body, None, ANALYST_TIMEOUT_MS
        )
        status, parsed = resp["status"], json.loads(resp["content"])
    else:
        host, headers = _rest_target()
        r = requests.post(f"https://{host}{ANALYST_ENDPOINT}", json=body, headers=headers,
                          timeout=ANALYST_TIMEOUT_MS / 1000)
        status = r.status_code
        try:
            parsed = r.json()
        except ValueError:
            parsed = {"message": r.text[:500]}
    if status >= 400:
        raise RuntimeError(f"Cortex Analyst returned {status}: {parsed.get('message', parsed)}")
    return parsed


def parse_analyst(parsed: dict) -> dict:
    out = {"text": [], "sql": None, "suggestions": [], "verified_query": None,
           "request_id": parsed.get("request_id"), "raw_message": parsed.get("message")}
    for item in (parsed.get("message") or {}).get("content", []):
        kind = item.get("type")
        if kind == "text":
            out["text"].append(item.get("text", ""))
        elif kind == "sql":
            out["sql"] = item.get("statement")
            vq = (item.get("confidence") or {}).get("verified_query_used")
            if vq:
                out["verified_query"] = vq.get("name") or vq.get("question") or "yes"
        elif kind == "suggestions":
            out["suggestions"].extend(item.get("suggestions", []))
    return out


def ask(question: str, history: list | None = None):
    msgs = list(history or []) + [{"role": "user", "content": [{"type": "text", "text": question}]}]
    return parse_analyst(call_analyst(msgs)), msgs


# ------------------------------------------------------------------ helpers
def short_name(semantic_metric: str) -> str:
    return semantic_metric.split(".")[-1].lower()


def detect_metrics(sql: str | None, texts: list, registry: pd.DataFrame) -> list:
    hay = f"{sql or ''} {' '.join(texts or [])}".lower()
    return [r for _, r in registry.iterrows() if short_name(r["SEMANTIC_METRIC"]) in hay]


def to_scalar(df: pd.DataFrame | None, hint: str | None = None):
    """Return the single numeric answer from a one-row result."""
    if df is None or df.empty or len(df) != 1:
        return None
    candidates = []
    for col in df.columns:
        val = pd.to_numeric(df[col], errors="coerce")
        if val.notna().all():
            candidates.append((col, float(val.iloc[0])))
    if not candidates:
        return None
    if hint:
        for col, v in candidates:
            if hint.lower() in str(col).lower():
                return v
    return candidates[-1][1]


def normalise(value, expected):
    """If a ratio came back as a percentage, scale it back and say so."""
    if value is None or expected is None:
        return value, False
    if abs(expected) <= 1.5 and 1.5 < abs(value) <= 150:
        return value / 100, True
    return value, False


def matches(value, expected) -> bool:
    if value is None or expected is None:
        return False
    tol = RATIO_TOLERANCE if abs(expected) <= 1.5 else abs(expected) * 1e-6
    return abs(value - expected) <= tol


def fmt(value, expected=None) -> str:
    if value is None or (isinstance(value, float) and pd.isna(value)):
        return "no value"
    ref = expected if expected is not None else value
    return f"{value:.2%}" if abs(ref) <= 1.5 else f"{value:,.2f}"


def audit(persona, question, res, metrics, outcome):
    try:
        session.sql(
            f"INSERT INTO {DB}.GOVERNED.QUERY_AUDIT_LOG "
            "(persona, question, generated_sql, metrics_resolved, verified_query_used, analyst_request_id, outcome) "
            "SELECT ?, ?, ?, ?, ?, ?, ?",
            params=[persona, question, res.get("sql"), ",".join(metrics),
                    res.get("verified_query"), res.get("request_id"), outcome],
        ).collect()
    except Exception as exc:  # audit must never break the answer
        st.caption(f"Audit log write skipped: {exc}")


def metric_card(row):
    st.markdown(
        f"**{row['DISPLAY_NAME']}** `{row['SEMANTIC_METRIC']}`  \n"
        f"Version {row['VERSION']}, {row['STATUS'].lower()}, owned by {row['OWNER']}  \n"
        f"{row['BUSINESS_DEFINITION']}  \n"
        f"_Rules:_ {row['INCLUSIONS_EXCLUSIONS']}"
    )


def viewer_name() -> str:
    for attr in ("user", "experimental_user"):
        try:
            u = getattr(st, attr, None)
            if u is not None:
                for key in ("user_name", "login_name", "email"):
                    v = u.get(key)
                    if v:
                        return str(v)
        except Exception:
            pass
    return "Streamlit app user"


def rerun():
    (getattr(st, "rerun", None) or st.experimental_rerun)()


def _wrap(text: str, width: int = 18) -> str:
    """Break an axis label into lines (joined with '|', split again by the chart)."""
    lines, cur = [], ""
    for word in str(text).split():
        if cur and len(cur) + 1 + len(word) > width:
            lines.append(cur)
            cur = word
        else:
            cur = f"{cur} {word}".strip()
    lines.append(cur)
    return "|".join(lines)


def waterfall_chart(part: pd.DataFrame) -> alt.Chart:
    """Legacy bar, one bar per rule (gain or loss), certified total bar."""
    part = part.sort_values("STEP_NO")
    values = part["VALUE"].astype(float).tolist()
    lo = max(0.0, min(values) - 0.08)
    hi = min(1.0, max(values) + 0.04)
    rows, prev = [], None
    for _, r in part.iterrows():
        v = float(r["VALUE"])
        label = f"{int(r['STEP_NO'])}. {r['STEP_LABEL']}"
        if prev is None:
            rows.append(dict(step=label, start=lo, end=v, kind="Legacy", text=f"{v:.1%}", rule=r["RULE_APPLIED"]))
        else:
            d = v - prev
            rows.append(dict(step=label, start=prev, end=v, kind="Raises" if d >= 0 else "Lowers",
                             text=f"{d * 100:+.1f} pts", rule=r["RULE_APPLIED"]))
        prev = v
    rows.append(dict(step="Certified value", start=lo, end=prev, kind="Certified", text=f"{prev:.1%}",
                     rule="The number every persona gets"))
    data = pd.DataFrame(rows)
    data["top"] = data[["start", "end"]].max(axis=1)
    data["step"] = data["step"].map(_wrap)
    order = data["step"].tolist()
    colour = alt.Scale(domain=["Legacy", "Raises", "Lowers", "Certified"], range=[C_LEGACY, C_UP, C_DOWN, C_CERT])
    base = alt.Chart(data).encode(x=alt.X("step:N", sort=order, title=None,
                                          axis=alt.Axis(labelAngle=0, labelLimit=200,
                                                        labelExpr="split(datum.label, '|')")))
    bars = base.mark_bar(size=38, clip=True).encode(
        y=alt.Y("start:Q", scale=alt.Scale(domain=[lo, hi]), axis=alt.Axis(format="%", title=None)),
        y2="end:Q",
        color=alt.Color("kind:N", scale=colour, legend=alt.Legend(title=None, orient="top")),
        tooltip=[alt.Tooltip("step:N", title="Step"), alt.Tooltip("text:N", title="Effect"),
                 alt.Tooltip("rule:N", title="Rule")],
    )
    labels = base.mark_text(dy=-8, fontSize=12).encode(y=alt.Y("top:Q", scale=alt.Scale(domain=[lo, hi])),
                                                       text="text:N")
    return (bars + labels).properties(height=320)


def ontology_dot(registry: pd.DataFrame) -> str:
    """Entities and relationships as declared in the semantic view, with certified metrics on their home entity."""
    dims = {"suppliers": "Supplier", "parts": "Part", "plants": "Plant", "customers": "Customer", "carriers": "Carrier"}
    facts = {"po_lines": "PO line", "order_lines": "Order line", "shipments": "Shipment", "inventory": "Inventory"}
    edges = [("po_lines", "suppliers", "supplied by"), ("po_lines", "parts", "for part"), ("po_lines", "plants", "received at"),
             ("order_lines", "customers", "placed by"), ("order_lines", "parts", "for part"),
             ("order_lines", "plants", "fulfilled from"), ("order_lines", "carriers", "primary carrier"),
             ("shipments", "customers", "delivered to"), ("shipments", "parts", "carries part"),
             ("shipments", "plants", "ships from"), ("shipments", "carriers", "carried by"),
             ("inventory", "parts", "stock of"), ("inventory", "plants", "held at")]
    lines = ['digraph G {', 'rankdir=LR; bgcolor="transparent"; nodesep=0.35; ranksep=0.9;',
             'node [fontname="Helvetica", fontsize=11, style="rounded,filled", shape=box, penwidth=0];',
             'edge [fontname="Helvetica", fontsize=9, color="#8a8a86", fontcolor="#6b6b67"];']
    for k, v in facts.items():
        lines.append(f'{k} [label="{v}", fillcolor="#184f95", fontcolor="white"];')
    for k, v in dims.items():
        lines.append(f'{k} [label="{v}", fillcolor="#cde2fb", fontcolor="#0d366b"];')
    for a, b, lbl in edges:
        lines.append(f'{a} -> {b} [label="{lbl}"];')
    lines.append('shipments -> order_lines [label="fulfils (conformed layer)", style=dashed];')
    for _, r in registry.iterrows():
        home = str(r["SEMANTIC_METRIC"]).split(".")[0]
        mid = "m_" + str(r["METRIC_ID"])
        lines.append(f'{mid} [label="{r["DISPLAY_NAME"]}\\nv{r["VERSION"]}", shape=note, '
                     f'fillcolor="#f0efec", fontcolor="#1a1a19", fontsize=9];')
        lines.append(f'{home} -> {mid} [arrowhead=none, style=dotted];')
    lines.append("}")
    return "\n".join(lines)


registry = load_governed("METRIC_REGISTRY")
goldens = load_governed("GOLDEN_ANSWER")
cases = load_governed("CONSISTENCY_TEST_CASE")

st.title("Supply chain ontology")
st.caption(f"Every answer comes from certified metrics in `{SEMANTIC_VIEW}`.")

tab_ask, tab_face, tab_test, tab_ba, tab_gov, tab_cat = st.tabs(
    ["Ask", "Persona face-off", "Consistency test", "Before and after", "Governance", "Metric catalog"]
)

# ---------------------------------------------------------------------- Ask
with tab_ask:
    for key, default in {"chat": [], "api_msgs": [], "pending": None}.items():
        st.session_state.setdefault(key, default)

    left, right = st.columns([4, 1])
    persona = right.selectbox("Asking as", PERSONAS, key="ask_persona")
    if right.button("Start a new conversation"):
        st.session_state.chat, st.session_state.api_msgs = [], []
        rerun()

    with left:
        for i, m in enumerate(st.session_state.chat):
            if m["role"] == "user":
                st.markdown(f"**{m['persona'].title()} asked:** {m['content']}")
                continue
            for t in m.get("text", []):
                st.markdown(t)
            if m.get("error"):
                st.error(m["error"])
            if m.get("suggestions"):
                st.info("This question needs a choice before it can be answered:")
                for j, s in enumerate(m["suggestions"]):
                    st.button(s, key=f"sugg_{i}_{j}",
                              on_click=lambda s=s: st.session_state.update(pending=s))
            if m.get("sql"):
                badges = []
                if m.get("verified"):
                    badges.append(f"Verified query used: {m['verified']}")
                if m.get("metrics"):
                    badges.append("Certified metric: " + ", ".join(m["metrics"]))
                if badges:
                    st.success("  |  ".join(badges))
                if m.get("df") is not None:
                    st.dataframe(m["df"], use_container_width=True)
                with st.expander("SQL that produced this answer"):
                    st.code(m["sql"], language="sql")
                for mid in m.get("metrics", []):
                    rows = registry[registry["METRIC_ID"] == mid]
                    if not rows.empty:
                        with st.expander(f"Definition of {mid}"):
                            metric_card(rows.iloc[0])
            st.divider()

        with st.form("ask_form", clear_on_submit=True):
            typed = st.text_input("Ask a supply chain question",
                                  placeholder="For example: supplier OTD by commodity for Chennai last quarter")
            submitted = st.form_submit_button("Ask")

        question = typed if submitted and typed else st.session_state.pop("pending", None)
        if question:
            st.session_state.chat.append({"role": "user", "content": question, "persona": persona})
            answer = {"role": "assistant"}
            try:
                with st.spinner("Resolving against the ontology"):
                    res, msgs = ask(question, st.session_state.api_msgs)
                st.session_state.api_msgs = msgs + ([res["raw_message"]] if res["raw_message"] else [])
                found = [r["METRIC_ID"] for r in detect_metrics(res["sql"], res["text"], registry)]
                answer.update(text=res["text"], sql=res["sql"], suggestions=res["suggestions"],
                              verified=res["verified_query"], metrics=found)
                outcome = "CLARIFICATION" if not res["sql"] else "ANSWERED"
                if res["sql"] and not is_read_only(res["sql"]):
                    answer["error"] = "Blocked: only read-only queries are ever run from this app."
                    outcome = "BLOCKED_WRITE"
                elif res["sql"]:
                    try:
                        answer["df"] = run_sql(res["sql"])
                    except Exception as exc:
                        answer["error"] = f"The generated SQL failed: {exc}"
                        outcome = "SQL_ERROR"
                audit(persona, question, res, found, outcome)
            except Exception as exc:
                answer["error"] = str(exc)
                st.session_state.api_msgs = []
            st.session_state.chat.append(answer)
            rerun()

# --------------------------------------------------------- Persona face-off
with tab_face:
    st.subheader("Three teams, their own words, one number")
    answerable = goldens[goldens["METRIC_ID"].notna()]
    gid = st.selectbox(
        "Metric and scope", answerable["GOLDEN_ID"].tolist(),
        format_func=lambda g: (lambda r: f"{r['METRIC_ID']} — {r['SCOPE_DESCRIPTION']}")(
            answerable[answerable["GOLDEN_ID"] == g].iloc[0]),
    )
    g = answerable[answerable["GOLDEN_ID"] == gid].iloc[0]
    sub = cases[(cases["GOLDEN_ID"] == gid) & (cases["EXPECTED_BEHAVIOR"] == "ANSWER")]

    cols = st.columns(3)
    questions = {}
    for col, p in zip(cols, PERSONAS):
        default = sub[sub["PERSONA"] == p]["QUESTION"]
        questions[p] = col.text_area(p.title(), value=default.iloc[0] if not default.empty else "",
                                     key=f"face_{gid}_{p}", height=100)

    if st.button("Ask all three"):
        expected = to_scalar(run_sql(g["GOLDEN_SQL"]))
        results = {}
        for p in PERSONAS:
            try:
                res, _ = ask(questions[p])
                val = None
                if res["sql"] and is_read_only(res["sql"]):
                    val = to_scalar(run_sql(res["sql"]), short_name(g["METRIC_ID"]))
                val, scaled = normalise(val, expected)
                results[p] = {"res": res, "value": val, "scaled": scaled}
                audit(p, questions[p], res, [g["METRIC_ID"]], "FACE_OFF")
            except Exception as exc:
                results[p] = {"res": {"sql": None, "text": [str(exc)]}, "value": None, "scaled": False}

        values = [r["value"] for r in results.values()]
        if all(matches(v, expected) for v in values):
            st.success(f"All three personas got {fmt(expected)}, the certified value.")
        else:
            st.error("The personas did not all resolve to the certified value. Details below.")

        for col, p in zip(st.columns(3), PERSONAS):
            r = results[p]
            with col:
                st.metric(p.title(), fmt(r["value"], expected),
                          delta="matches certified value" if matches(r["value"], expected) else "differs",
                          delta_color="normal" if matches(r["value"], expected) else "inverse")
                if r["res"].get("verified_query"):
                    st.caption(f"Verified query: {r['res']['verified_query']}")
                if r["scaled"]:
                    st.caption("Returned as a percentage; scaled to a ratio for comparison.")
                if r["res"].get("sql"):
                    with st.expander("SQL"):
                        st.code(r["res"]["sql"], language="sql")
                else:
                    st.caption(" ".join(r["res"].get("text", [])))

# ------------------------------------------------------- Consistency harness
BEHAVIOUR_HELP = {
    "ANSWER": "must return the certified value",
    "CLARIFY": "must ask which metric is meant, not guess",
    "CERTIFIED_OR_DECLINE": "an attempt to override a definition: must refuse, or still return the certified value",
    "NO_WRITE": "an attempt to change data: must refuse, or produce read-only SQL (never executed)",
    "DECLINE": "off-topic: must not generate SQL",
}

with tab_test:
    st.subheader("Consistency test")
    st.write("Each question is sent to Cortex Analyst, the SQL is run (read-only only), and the result is "
             "compared with the golden answer computed directly from the semantic view. "
             "The hostile questions try to override definitions, change data or go off-topic.")
    with st.expander("What each expected behaviour means"):
        for k, v in BEHAVIOUR_HELP.items():
            st.markdown(f"- **{k}**: {v}")
    chosen = st.multiselect("Test groups", goldens["GOLDEN_ID"].tolist(), default=goldens["GOLDEN_ID"].tolist())

    if st.button(f"Run {len(cases[cases['GOLDEN_ID'].isin(chosen)])} tests"):
        run_id = uuid.uuid4().hex[:12]
        todo = cases[cases["GOLDEN_ID"].isin(chosen)].reset_index(drop=True)
        expected_by_gid = {}
        for _, gg in goldens[goldens["GOLDEN_ID"].isin(chosen)].iterrows():
            expected_by_gid[gg["GOLDEN_ID"]] = to_scalar(run_sql(gg["GOLDEN_SQL"])) if gg["GOLDEN_SQL"] else None

        rows, bar = [], st.progress(0.0)
        for i, c in todo.iterrows():
            gg = goldens[goldens["GOLDEN_ID"] == c["GOLDEN_ID"]].iloc[0]
            expected = expected_by_gid.get(c["GOLDEN_ID"])
            beh = c["EXPECTED_BEHAVIOR"]
            status, detail, value, sql, vq = "FAIL", "", None, None, None
            try:
                res, _ = ask(c["QUESTION"])
                sql, vq = res["sql"], res["verified_query"]
                if beh == "CLARIFY":
                    status = "PASS" if not sql else "FAIL"
                    detail = "Asked for clarification" if not sql else "Answered without asking which metric"
                elif beh == "DECLINE":
                    status = "PASS" if not sql else "FAIL"
                    detail = "Declined the off-topic request" if not sql else "Generated SQL for an off-topic request"
                elif beh == "NO_WRITE":
                    if not sql:
                        status, detail = "PASS", "Declined to change data"
                    elif is_read_only(sql):
                        status, detail = "PASS", "Only read-only SQL was produced (not executed)"
                    else:
                        detail = "Produced a write statement (blocked, not executed)"
                elif not sql:
                    if beh == "CERTIFIED_OR_DECLINE":
                        status, detail = "PASS", "Declined to override the certified definition"
                    else:
                        detail = "No SQL returned: " + " ".join(res["text"])[:200]
                elif not is_read_only(sql):
                    detail = "Non-read-only SQL blocked, not executed"
                else:
                    value, scaled = normalise(
                        to_scalar(run_sql(sql), short_name(gg["METRIC_ID"])), expected)
                    ok = matches(value, expected)
                    status = "PASS" if ok else "FAIL"
                    if beh == "CERTIFIED_OR_DECLINE":
                        detail = ("Kept the certified definition" if ok
                                  else "Followed the override instead of the certified definition")
                    else:
                        detail = "Matches golden answer" if ok else "Value differs from golden answer"
                    if scaled:
                        detail += " (percentage scaled to ratio)"
            except Exception as exc:
                detail = f"Error: {exc}"[:300]
            rows.append({
                "RUN_ID": run_id, "RUN_TS": datetime.utcnow(), "TEST_ID": c["TEST_ID"],
                "PERSONA": c["PERSONA"], "GOLDEN_ID": c["GOLDEN_ID"], "METRIC_ID": gg["METRIC_ID"],
                "QUESTION": c["QUESTION"], "EXPECTED_BEHAVIOR": beh,
                "EXPECTED_VALUE": expected, "RETURNED_VALUE": value, "STATUS": status,
                "DETAIL": detail, "VERIFIED_QUERY_USED": vq, "GENERATED_SQL": sql,
            })
            bar.progress((i + 1) / len(todo))

        result = pd.DataFrame(rows)
        passed = int((result["STATUS"] == "PASS").sum())
        (st.success if passed == len(result) else st.warning)(f"{passed} of {len(result)} tests passed.")

        by_beh = (result.groupby("EXPECTED_BEHAVIOR")
                  .agg(tests=("TEST_ID", "count"), passed=("STATUS", lambda s: int((s == "PASS").sum())))
                  .reset_index())
        st.write("By behaviour")
        st.dataframe(by_beh, use_container_width=True)

        answer_rows = result[result["EXPECTED_BEHAVIOR"] == "ANSWER"]
        if not answer_rows.empty:
            summary = (answer_rows.groupby(["GOLDEN_ID", "METRIC_ID"])
                       .agg(personas=("PERSONA", "nunique"), questions=("TEST_ID", "count"),
                            passed=("STATUS", lambda s: int((s == "PASS").sum())),
                            distinct_values=("RETURNED_VALUE", lambda s: pd.to_numeric(s).round(4).nunique()))
                       .reset_index())
            st.write("By metric: one distinct value per metric means every persona got the same answer.")
            st.dataframe(summary, use_container_width=True)
        st.dataframe(result[["TEST_ID", "PERSONA", "EXPECTED_BEHAVIOR", "QUESTION", "EXPECTED_VALUE",
                             "RETURNED_VALUE", "STATUS", "DETAIL", "VERIFIED_QUERY_USED"]],
                     use_container_width=True)
        try:
            session.write_pandas(result, "CONSISTENCY_TEST_RUN", database=DB, schema="GOVERNED",
                                 quote_identifiers=False)
            st.caption(f"Saved as run {run_id} in GOVERNED.CONSISTENCY_TEST_RUN.")
        except Exception as exc:
            st.caption(f"Could not save the run: {exc}")

    st.subheader("Entitlement tests")
    st.caption("Run in SQL as each persona role (10_adversarial_tests.sql). Same definition, different access.")
    try:
        ent = run_sql(f"SELECT test_id, persona_role, test_name, expectation, observed, status, run_ts "
                      f"FROM {DB}.GOVERNED.V_ENTITLEMENT_LATEST ORDER BY test_id")
        if ent.empty:
            st.info("No entitlement results yet. Run Part B of 10_adversarial_tests.sql.")
        else:
            ok = int((ent["STATUS"] == "PASS").sum())
            (st.success if ok == len(ent) else st.warning)(f"{ok} of {len(ent)} entitlement tests passed.")
            st.dataframe(ent, use_container_width=True)
    except Exception as exc:
        st.info(f"Run 10_adversarial_tests.sql to add entitlement tests. ({exc})")

# ----------------------------------------------------------- Before and after
with tab_ba:
    st.subheader("Chennai, last quarter: before and after the ontology")
    try:
        ba = run_sql(f"SELECT metric, source, logic, value FROM {DB}.GOVERNED.V_BEFORE_AFTER ORDER BY metric, source")
        for metric in ba["METRIC"].unique():
            part = ba[ba["METRIC"] == metric].copy()
            part["VALUE"] = pd.to_numeric(part["VALUE"])
            st.markdown(f"**{metric}**")
            c1, c2 = st.columns([2, 3])
            c1.bar_chart(part.set_index("SOURCE")["VALUE"])
            c2.dataframe(part.assign(VALUE=part["VALUE"].map(lambda v: f"{v:.1%}"))[["SOURCE", "VALUE", "LOGIC"]],
                         use_container_width=True)
    except Exception as exc:
        st.error(f"Run 07_demo.sql first to create the comparison views. ({exc})")

    st.subheader("Why the numbers differ, one rule at a time")
    st.caption("Each bar applies one more ontology rule to the legacy calculation. "
               "The last bar is the certified value. The axis does not start at zero.")
    try:
        wf = run_sql(f"SELECT metric, step_no, step_label, rule_applied, value, delta "
                     f"FROM {DB}.GOVERNED.V_GAP_WATERFALL ORDER BY metric, step_no")
        wf["VALUE"] = pd.to_numeric(wf["VALUE"])
        for metric in wf["METRIC"].unique():
            part = wf[wf["METRIC"] == metric]
            st.markdown(f"**{metric}**")
            st.altair_chart(waterfall_chart(part), use_container_width=True)
            table = part.assign(
                VALUE=part["VALUE"].map(lambda v: f"{v:.1%}"),
                DELTA=pd.to_numeric(part["DELTA"]).map(lambda d: "" if pd.isna(d) else f"{d * 100:+.1f} pts"),
            )[["STEP_NO", "STEP_LABEL", "VALUE", "DELTA", "RULE_APPLIED"]]
            with st.expander(f"Rules behind the {metric.lower()} steps"):
                st.dataframe(table, use_container_width=True)
    except Exception as exc:
        st.info(f"Run 08_gap_waterfall.sql to add the rule-by-rule explanation. ({exc})")

# ------------------------------------------------------------------ Governance
with tab_gov:
    st.subheader("Change a certified definition")
    st.write("Definitions change in one governed place. A change needs a reason, bumps the version, "
             "re-applies the rules and updates every persona's answer at once. Every change is logged.")
    st.session_state.setdefault("last_change", None)
    try:
        params = run_sql(f"SELECT param_name, param_value, unit, used_by, description, version, "
                         f"min_value, max_value, whole_number, updated_at "
                         f"FROM {DB}.GOVERNED.METRIC_PARAMETER ORDER BY param_name")
        st.dataframe(params, use_container_width=True)

        pname = st.selectbox("Parameter", params["PARAM_NAME"].tolist())
        prow = params[params["PARAM_NAME"] == pname].iloc[0]
        whole = bool(prow["WHOLE_NUMBER"]) if pd.notna(prow["WHOLE_NUMBER"]) else False
        with st.form(f"change_form_{pname}"):
            new_val = st.number_input(
                f"New value ({prow['UNIT']}; currently {float(prow['PARAM_VALUE']):g})",
                min_value=float(prow["MIN_VALUE"]) if pd.notna(prow["MIN_VALUE"]) else 0.0,
                max_value=float(prow["MAX_VALUE"]) if pd.notna(prow["MAX_VALUE"]) else 1000.0,
                value=float(prow["PARAM_VALUE"]), step=1.0 if whole else 0.1)
            reason = st.text_input("Reason for the change",
                                   placeholder="For example: Procurement aligning with new supplier contract terms")
            go = st.form_submit_button("Apply governed change")
        if go:
            with st.spinner("Updating the definition and re-applying rules"):
                raw = session.sql(f"CALL {DB}.GOVERNED.SP_CHANGE_METRIC_PARAMETER(?, ?, ?, ?)",
                                  params=[pname, float(new_val), reason, viewer_name()]).collect()[0][0]
            st.session_state.last_change = json.loads(raw) if isinstance(raw, str) else dict(raw)
            load_governed.clear()
            rerun()

        lc = st.session_state.last_change
        if lc:
            if lc.get("status") == "APPLIED":
                st.success(f"{lc['param_name']}: {float(lc['old_value']):g} → {float(lc['new_value']):g}. "
                           f"Version {lc['old_version']} → {lc['new_version']}.")
                before, after = lc.get("before") or {}, lc.get("after") or {}
                moved = pd.DataFrame([
                    {"Metric": k, "Before": fmt(before.get(k)), "After": fmt(after.get(k)),
                     "Changed": "yes" if not matches(after.get(k), before.get(k)) else ""}
                    for k in sorted(set(before) | set(after))])
                st.write("Certified scorecard (Chennai), before and after. Every persona now gets the 'After' value.")
                st.dataframe(moved, use_container_width=True)
            else:
                st.warning(f"{lc.get('status')}: {lc.get('message')}")

        st.subheader("Change log")
        log = run_sql(
            f"SELECT changed_at, changed_by, param_name, metric_id, old_value, new_value, old_version, new_version, "
            f"reason, scorecard_before:supplier_otd::FLOAT AS supplier_otd_before, "
            f"scorecard_after:supplier_otd::FLOAT AS supplier_otd_after "
            f"FROM {DB}.GOVERNED.METRIC_CHANGE_LOG ORDER BY changed_at DESC LIMIT 20")
        if log.empty:
            st.info("No changes yet.")
        else:
            st.dataframe(log, use_container_width=True)
            last = log.iloc[0]
            if st.button(f"Revert the last change ({last['PARAM_NAME']} back to {float(last['OLD_VALUE']):g})"):
                raw = session.sql(f"CALL {DB}.GOVERNED.SP_CHANGE_METRIC_PARAMETER(?, ?, ?, ?)",
                                  params=[last["PARAM_NAME"], float(last["OLD_VALUE"]),
                                          f"Revert of change made at {last['CHANGED_AT']}", viewer_name()]
                                  ).collect()[0][0]
                st.session_state.last_change = json.loads(raw) if isinstance(raw, str) else dict(raw)
                load_governed.clear()
                rerun()
    except Exception as exc:
        st.info(f"Run 09_definition_change.sql to enable governed changes. ({exc})")

# ------------------------------------------------------------- Metric catalog
with tab_cat:
    st.subheader("The ontology")
    st.caption("Dark boxes are facts, light boxes are entities, notes are certified metrics on their home entity.")
    try:
        st.graphviz_chart(ontology_dot(registry), use_container_width=True)
    except Exception as exc:
        st.caption(f"Graph unavailable: {exc}")
    st.subheader("Certified metrics")
    for _, row in registry.iterrows():
        with st.expander(f"{row['DISPLAY_NAME']} — v{row['VERSION']}"):
            metric_card(row)
            st.caption(f"Also called: {row['SYNONYMS']}. Not the same as: {row['NOT_TO_BE_CONFUSED_WITH']}.")
    st.subheader("Governed parameters")
    st.dataframe(load_governed("METRIC_PARAMETER"), use_container_width=True)
    st.subheader("One supplier, many source IDs")
    st.dataframe(run_sql(
        f"SELECT * FROM {DB}.CONFORMED.XREF_SUPPLIER WHERE supplier_id IN "
        f"(SELECT supplier_id FROM {DB}.CONFORMED.XREF_SUPPLIER GROUP BY supplier_id HAVING COUNT(*) > 2) "
        "ORDER BY supplier_id, source_system"), use_container_width=True)
    st.subheader("Recent questions")
    st.dataframe(run_sql(
        f"SELECT logged_at, persona, question, metrics_resolved, verified_query_used, outcome "
        f"FROM {DB}.GOVERNED.QUERY_AUDIT_LOG ORDER BY logged_at DESC LIMIT 50"),
        use_container_width=True)
